name: Pacman Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hugomd/pacman-contribution-graph@master
        with:
          github_user_name: vedantberiwal23
          gif_out_path: dist/pacman.gif
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate Pacman
          branch: output
